# Generated by Django 3.1.7 on 2021-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ptt_stock_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
