# Generated by Django 3.1.7 on 2021-04-13 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pttstock_comments_analize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptt_stock_comments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
